- infrastructure/template.yaml
Give the account management API stub a domain in our dev and build environments so the frontend can reach it.
This is following the same pattern as we used for the domain at the frontend (see https://github.com/alphagov/di-account-management-frontend/blob/main/deploy/template.yaml#L736-L770).
The firewall rules on the frontend app stop it from making requests to any non-`*.gov.uk` domains. This means requests to the stub API were timing out and I was seeing 504 errors when testing the frontend.
I've deployed the following stack to dev as `alex-stub-domain-test` which sets up a domain for the stub in dev:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "A test stack to add a domain to API Gateway."
Parameters:
Environment:
Description: "The …
```
> OLH-874: Give the AM API stub a domain

- infrastructure/template.yaml
These lambdas are for our stub functions and we don't care about saving requests if anything goes wrong.
Currently the pipeline is refusing to deploy this stack because this rule is failing, so skip it for the stub lambdas.
We do have the pipeline [set to `CONTINUE` on a Checkov failure](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3138355242/SAM+deploy+pipeline+parameters+table), but that doesn't seem to be working at the moment. It might take the dev platform team a few days to figure that out so let's skip the rules for now to keep our work unblocked.
> OLH-874: Skip DLQ Checkov checks

- infrastructure/template.yaml
- Update the oidc authorise stub to use the OidcStubsRestApi Gateway .
You can do a GET request on `https://oidc-stub.home.dev.account.gov.uk/authorize` and it should return [home.dev.account.gov.uk](https://home.dev.account.gov.uk)
> Remove the Oidc API Gateway and point to OidcRestApi

- .github/workflows/lint-and-test-lambdas.yaml
- infrastructure/template.yaml
- oidc/configuration/.eslintrc.json
- oidc/configuration/.gitignore
- oidc/configuration/jest.config.ts
- oidc/configuration/oidc-config-stub.ts
- oidc/configuration/package-lock.json
- oidc/configuration/package.json
- oidc/configuration/tests/oidc-config-stub.test.ts
- oidc/configuration/tsconfig.json
**What changed**
OIDC Config Stub is a lambda that returns the OIDC configuration information for the stubbed APIs. It's a mainly static file but has dynamic urls based on environment.
also:
- Infrastructure for the lambda including api gateway
**Issue tracking**
[OLH-920](https://govukverify.atlassian.net/browse/OLH-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
**Testing**
To test use this url: https://oidc-stub.home.dev.account.gov.uk/.well-known/openid-configuration
[OLH-920]: https://govukverify.atlassian.net/browse/OLH-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OLH-920 OIDC config stub

- .github/workflows/lint-and-test-lambdas.yaml
- oidc/authorize/oidc-authorize-stub.ts
- oidc/authorize/package-lock.json
- oidc/authorize/package.json
- oidc/authorize/tests/oidc-authorize-stub.test.ts
Improving unit tests on the Authz stub and adding to to the lint-and-test action.
See below it has passed the test. 
I have not tested the body of the event sent to SQS because the message contains a timestamp and a UUID which are generated by the code. The test would have to check it passes a regex or other pattern and this was getting complex while adding little value as this is only a stub.
> add oidc authz lambda to lint and test action

- oidc/authorize/oidc-authorize-stub.ts
This lambda wasn't sending the message to SQS before returning which meant the stub wasn't triggering the backend. `sendSqSMessage` is an async function so we need to `await` it to make sure it's finished before carrying on.
I've deployed this change to dev and seen in the [SQS / lambda logs](https://eu-west-2.console.aws.amazon.com/lambda/home?region=eu-west-2#/functions/dev-account-mgmt-backend-save-raw-events?tab=monitoring) that the backend is now running when I log into the frontend.
> OLH-875: Wait for SQS message to be sent

- oidc/userinfo/models.ts
- oidc/userinfo/oidc-userinfo-stub.ts
Update the phone number claim name to match what the frontend is expecting.
The frontend is currently not storing the user's phone number in the session once it's made the request to the `/userinfo` endpoint.
This means we're not displaying the 'change your phone number' flow and the frontend is behaving as if the user has an authenticator app.
Our [public documentation][1] says that the phone number claim is called `phone`, however the [OIDC specification][2] says it should be `phone_number`.
This is a mistake in our documentation and the frontend is expecting `phone_number`.
[Our public documentation][1]
[OIDC specification][2] 
I've deployed this branch to dev and pointed my local frontend at the branch. You can see the phone number field now:
[1]: …
> OLH-1026: Fix phone_number claim name

- oidc/configuration/oidc-config-stub.ts
Use a real URL for the end session field in the OIDC configuration.
Currently when a user clicks the 'Sign out' button using the stub they end up on an error page because the OIDC end session endpoint in our configuration file doesn't exist.
Rather than writing a new lambda as part of this stub API, send the user directly to the Auth team's frontend to see the sign out page. This intentionally uses the build environment as there isn't an equivalent for dev.
This link goes straight to the user-facing page and doesn't hit the actual build OIDC end session URL. This is intentional as our user doesn't have a session with the real OIDC server and I didn't want to run the risk of seeing any errors or getting our browser cookies in an odd state. It does mean there's a bunch of URL parameters …
> OLH-1027: Use a real page for logout

- .github/workflows/sam-app-post-merge-actions.yaml
Don't run the post-merge tests in subfolder.
We missed this in https://github.com/govuk-one-login/account-management-stubs/pull/30
> OLH-1619: Don't run the post-merge tests in subfolder

- src/method-management/method-management.ts
- src/tests/method-management/method-management.test.ts
- template.yaml
Adds a new POST route to the stub API, to mimic the "create MFA method" endpoint.
So that we can develop and test the frontend flow.
Deploying to dev, and testing the API in the CLI
> OLH-1661 - Add stub for the create MFA Method endpoint

- template.yaml
Increase retention of LogGroup to 30 days. Currently any log retention that is set under 30 days will be set to 30 by a Lambda attached to the LZA Lambda run. [SW-284](https://govukverify.atlassian.net/browse/SW-284)
- increase RetentionInDays from 1 to 30 days.
LZA lambda increase log retention to 30 days. If it is 30 days or more it is ignored.
[INCIDEN-627](https://govukverify.atlassian.net/browse/INCIDEN-627)
[SW-284]: https://govukverify.atlassian.net/browse/SW-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INCIDEN-627]: https://govukverify.atlassian.net/browse/INCIDEN-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SW-284: Increase retention of LogGroup to 30 days.

- src/oidc/authorize.ts
- src/scenarios/scenarios.ts
Auto delete entries into the oidc nonce dynamo db table after 24 hours by utilising the OOTB TTL feature which requires us to populate the field with a epoch time.
1. Generation of epoch time (current + 24 hours)
2. Send remove at time with nonce session data 
3. Handled by Dynamo DB - auto delete after 24 hours of rows
Auto delete of rows in DynamoDb for the oidc_stub_data table after 24 hours.
Reduce long term data storage costs and possibly read request cost.
(https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html)
1. Tested remove_at value was populated with the correct epoch time (+24 hours)
2. Noted code e46ef20e-7212-4c97-977d-9aaff87a07e9 which had the remove at value of 1716647044
3. (PENDING) verified it's deletion over the weekend.
NA
> OLH-1822-remove-stub-sessions-from-dynamo-db-after-24-hours

- src/method-management/method-management.ts
- src/oidc/userinfo.ts
- src/scenarios/scenarios-utils.ts
- src/scenarios/scenarios.interfaces.ts
- src/scenarios/scenarios.ts
- src/tests/method-management/method-management.test.ts
- template.yaml
- Addition of 3 new user scenarios: errorMfa400, errorMfa404, errorMfa500
- Refactored scenario code
- Depending on which user you are logged in with you will always get the error response code for create and update.
- Ability to test different error codes from the mfa api on our frontend
- Added unit test to validate correct error codes are returned
- Validated when updating the cloudwatch logs for the update lambda returned a 400
- NOTE: front end dev console still says there was a 500 error even if a 400 error was suggested. Open to suggestions to further debug, may be front end?
> OLH-1797-add-some-error-responses-to-the-stub

- src/oidc/token.ts
- src/oidc/validate-token.ts
- src/tests/oidc/token.test.ts
- src/tests/oidc/validate-token.test.ts
OLH-1828 - Add additional checks to Stubs to validate the client assertion token
Before generating a token, the stub now checks that
1. All required parameters are provided in the /token call
2. No duplication of parameters in the /token call
3. client assertion JWT token is parsable and retrieves the issuer
4. Verifies issuers matches the client id for the environment
5. Verifies redirect URL is supported by the stubs
6. Verifies grant type provided is supported
So that OIDC checks in the dev environment using stubs can match as closely as possible to the same check live oidc performs before validating a token request and returning the rewuired access token
https://govukverify.atlassian.net/browse/OLH-1930
https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/authenti …
> OLH-1828 - Add additional checks to Stubs

- docs/oidc/openapi.yaml
- src/scenarios/scenarios.interfaces.ts
- src/scenarios/scenarios.ts
Remove `updated_at` from userinfo response. 
This field is an optional one in the OIDC spec. Our public tech docs say it's present in our real response, but this is a mistake. In the real version of our OIDC IdP we don't include `updated_at`.
I couldn't find any reference to us using this value in the frontend (which makes sense if it's not provided) so this PR won't break our pre-staging environments.
See [this Slack conversation](https://gds.slack.com/archives/C012GEZBZM0/p1720706277498139).
> BAU: Remove `updated_at` from userinfo response

- .github/PULL_REQUEST_TEMPLATE.md
- .husky/_/husky.sh
- src/common/validation.ts
- src/method-management/method-management.ts
- src/method-management/models/schema.d.ts
- src/tests/common/validation.test.ts
- src/tests/method-management/method-management.test.ts
[OLH-1966] Stub updates for make backup MFA method the default MFA method
Updated schema from latest openapi-specs repo.
Added more validation for missing required fields and added 404 and 500 handlers
To make the stubs behave as the actual openapi-specs endpoint
Tested locally and in dev
Send payloads that match 404 and 500 server errors from API schema page https://symmetrical-adventure-q4wnm7e.pages.github.io/?urls.primaryName=openapi-specs-method-management-api#/2FAManagement/mfa-methods-update
[OLH-1966]: https://govukverify.atlassian.net/browse/OLH-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OLH-1966 Stub updates for make backup MFA method the default MFA method

- template.yaml
Many of our stub lambdas have the same permissions requirements; we have lots with no extra permissions and all the method management ones need permission to query the DynamoDB table.
Reduce the complexity and length of our template by:
- Adding a base execution role with no extra AWS permissions and using this where possible
- Adding a single managed policy that grants permission to read from the DynamoDB table
- Adding a single execution role that has the base permissions and the policy to read from the DynamoDB table
This allows us to delete a lot of the duplicate per-lambda roles and IAM policies. The permissions for each lambda hasn't changed as a result of this; it's purely how we organise and assign those permissions.
I'll deploy this branch to dev and check the stubs still work as …
> BAU: Consolidate lambda roles and policies

- template.yaml
Deployed branch to the demo environment and the the error in the pipeline was fixed. 
[PSREDEV-1270]: https://govukverify.atlassian.net/browse/PSREDEV-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PSREDEV-1270: added TxmaDummyInputQueue values for demo env

- src/scenarios/scenarios.ts
Add a testing scenario to test the case where the user enter's the OTP code incorrectly (for example, when changing their phone number)
> OLH-2019 Incorrect OTP scenario

- src/method-management/method-management.ts
- src/tests/method-management/method-management.test.ts
OLH-1996 - Stub updates for replace a default MFA method
https://govukverify.atlassian.net/browse/OLH-1996
Update stub to permit change of default method
So that we can simulate calls to change the default MFA method of a user prior to the real API being available.
Deploy to dev, attempt to change default method and ensure it works.
> OLH-1996 - Stub updates for replace a default MFA method

- src/scenarios/scenarios-utils.ts
- template.yaml
[OLH-2065]: Improve Lambda performance
Ran performance tests against dev. Identified Lambda's were under provisioned and rightsized them. Additionally refactored some code so it has better performance.
Lambda's were taking 1.8s to run in the 99th percentile. 
Deployed to Dev. 
Validated performance improvement.
[OLH-2065]: https://govukverify.atlassian.net/browse/OLH-2065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OLH-2065-help-performance-testing-team-fix-99-test-failures-after-introducing-the-stub-page

- src/scenarios/scenarios-utils.ts
- src/scenarios/scenarios.ts
[OLH-2114] Resolve activity history
created a performance test user with randomly generated session id
Missing activity history from default user
Tested in dev environment
[OLH-2114]: https://govukverify.atlassian.net/browse/OLH-2114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OLH-2114-activity-history-not-being-stored-with-oidc

- .github/dependabot.yml
[OLH-2272] Update Dependabot config for the stub 
Duplicated config from frontend and backend to the stub so updates are grouped.
Merging individual branches triggered rebasing which meant additional waiting to resolve dependabot recommendations.
[OLH-2272]: https://govukverify.atlassian.net/browse/OLH-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OLH-2272-update-dependabot-config-for-the-stub-to-group-updates

- template.yaml
[OLH-2181] Increased provisioned concurrency for OIDC Scenario Lambda
Increased number of provisioned concurrency instances to 5
Cold starts were impacting auth flow which caused signing in to not meet the NFR. Though it is a stub, this will ensure the performance of the site is focused on the actual site.
[OLH-2181]: https://govukverify.atlassian.net/browse/OLH-2181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Olh 2181: Increase provisioned concurrency for oidc scenario lambda

- .github/workflows/sonarcloud.yaml
The sonarcloud-github-action is now deprecated. The recommendation is to replace it with the sonarqube-scan-action. This should work as a drop-in replacement.
Implemented Sonarqube Scan to prepare for migration when our existing sonarqube cloud action is deprecated.
Sonarqube Cloud Action is being deprecated and replaced with Sonarqube scan.
https://github.com/sonarsource/sonarcloud-github-action
Workflow working in this PR.
> BAU: replace sonarqube cloud with sonarqube scan

- template.yaml
From Node 18 as that's about to be deprecated. Our policy[^1] says we should be on the most recent LTS runtime, so that's Node 22.
This is a safe upgrade as we already run our tests locally and in CI using Node 22.
I've taken the opportunity to move this parameter to the `Globals` object as all these Lambdas use the same runtime.
[^1]: https://team-manual.account.gov.uk/policies/#active-policies
Node 18 is EOL in September
> OLH-2538: Upgrade Lambda runtime to Node 22

- src/method-management/method-management.ts
- template.yaml
Update the URLs in our stubs to match and pick up the new path parameter in the retrieve handler.
We'll also need to update the other methods to use the ID from the path. My plan is to validate this change with the retrieve method, then I'll update the rest in a followup PR.
I've released this branch to dev and verified the frontend does now pick up the user's MFA methods:
The URL structure of the API has changed to include the public subject ID in the path, rather than the API inferring it from the auth token.
[API spec](https://github.com/govuk-one-login/openapi-specs/blob/main/auth/account-management-api/account-management-with-mfa-method-management.yaml#L69)
> OLH-2534: Update the MFA API url structure

- src/scenarios/scenarios.ts
- template.yaml
Fix the bug where a user signed in through the stubs, saw the correct MFA details then signed out, picked a new scenario but saw the same MFA details as in their previous session. There are two fixes in this PR:
1. Use a unique user ID for each scenario. These IDs are the same format that we expect from GOV.UK One Login in production but include the scenario name for readability.
2. Disable caching on the API Gateway. The old call to retrieve a user's methods was a POST which wasn't cached but the new one is a GET which was.
These changes eliminate the chance of caching both at the API and in the frontend session (where we have an index on user ID)
> OLH-2534: Fix the bug where signing out doesn't update your MFA methods

- src/method-management/method-management.ts
- src/tests/method-management/method-management.test.ts
- template.yaml
This is a followup to #444 which updates all the other stub endpoints to the new API spec. 
The updated API design now has the user's public subject ID in the URL for all API methods. This means these stubs no longer need to use the access token to look up which scenario they need to respond with - they now just look it up using the public subject ID. _That_ means I've been able to remove their DynamoDB permissions as well as tidy up the code.
#444 
[API spec](https://github.com/govuk-one-login/openapi-specs/blob/main/auth/account-management-api/account-management-with-mfa-method-management.yaml) 
I've deployed this branch to dev and clicked through a couple of the updated journeys. They all seemed to work ok.
There's quite a few changes here, but it should be clear if you review commit …
> OLH-2534: Update remaining method management stubs for the new API spec

- src/method-management/method-management.ts
- src/tests/method-management/method-management.test.ts
When parsing the request body for MFA method updating the data is should be extracted from the nested property `mfaMethod` in order to match the OpenAPI spec.
> Fix: update MFA details are nested under mfaMethod

- src/method-management/method-management.ts
Don't expect `mfaMethodType` in update requests
Following https://github.com/govuk-one-login/di-account-management-frontend/pull/2170 not every PUT request to the method management API will include an `mfaMethodType` parameter, as this is no longer required when we're switching a method from backup to default.
> OLH-2592: Don't expect `mfaMethodType` in update requests

- src/account-management-api/all-routes.ts
- src/common/response-utils.ts
- src/method-management/method-management.ts
- src/scenarios/scenarios-utils.ts
- src/scenarios/scenarios.interfaces.ts
- src/scenarios/scenarios.ts
- src/tests/account-management-api/all-routes.test.ts
- src/tests/method-management/method-management.test.ts
OLH-2627 Account Management Stubs - Create stub scenarios for intervened users
Update the stubs to handle incoming request to authenticate endpoint to ensure  accounts with suspended or blocked interventions returns an appropriate response
Support the AIS Data Integrity initiative
https://govukverify.atlassian.net/browse/OLH-2627
Deploy the stub to dev environment and ensure all existing functionality still works. Implementation of these changes will be done as part of https://govukverify.atlassian.net/browse/OLH-2626
> OLH-2627 Account Management Stubs - Create stub scenarios for intervened users

- docs/oidc/openapi.yaml
- src/common/response-utils.ts
- src/common/validation.ts
- src/oidc/configuration.ts
- src/oidc/logout.ts
- src/tests/common/validation.test.ts
- src/tests/oidc/logout.test.ts
- template.yaml
'Handle' OIDC logout requests that include a `post_logout_redirect_uri` parameter by validating the domain and simply redirecting the user back to that URI. This adds a new Lambda and API Gateway route that's published in the OIDC configuration.
This is compliant with the logout interface described in [our public tech documentation](https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/managing-your-users-sessions/#make-a-request-to-log-your-user-out-of-gov-uk-one-login).
We need to do the domain validation here to protect ourselves from an [open redirect attack](https://hacksplaining.com/prevention/open-redirects). We need to be extra carfeul here as we allow redirects to `localhost`. If an attacker's got a webserver running on a user's machine then that user is …
> OLH-2655: Handle OIDC logout requests

- template.yaml
- Correct logout redirect URLs from `/logout-return` to `/logout-redirect`
- Support localhost redirect URL in dev
https://govukverify.atlassian.net/browse/OLH-2683
> OLH-2683: Update logout redirect URLs

- src/scenarios/scenarios.ts
[OLH-2627] Permanently suspended user should return code 1084
Switched scenario to blocked true
This user should return code 1084 but it is returning the same as the temp suspended user.
[OLH-2627]: https://govukverify.atlassian.net/browse/OLH-2627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OLH-2627] Permanently suspended user should return code 1084

- src/method-management/method-management.ts
- src/tests/method-management/method-management.test.ts
Validates the phone number and OTP code when creating an SMS MFA method
To ensure that the parameters sent in the request align with what is expected in the real world
> Validate phone number and OTP code when creating SMS MFA method

- template.yaml
Add tags to stubs APIs so that they FMS WAFs get associated with custom WAF in dev env only.
API Resources have new tags with propagation to stages
Confirm with GDS non-prod WAF policy managed by FMS
https://github.com/govuk-one-login/account-management-stubs/pull/532
https://github.com/govuk-one-login/account-management-stubs/pull/531
Deployed to dev using both `dev` and `build` environment parameter to check conditions work as expected
> OLH-3085: Added Regional Policy tags to stub APIs for dev only

- template.yaml
Reverts govuk-one-login/account-management-stubs#537
The frontend is too complex to migrate at this time, so we're going to migrate the stubs and backend back to the old VPC stack until it's necessary (likely when transit gateway comes along).
> Revert "OLH-2976: Use all 3 subnets in the new VPC"
