govuk-one-login/account-management-stubs

.github/workflows/lint-and-test-lambdas.yaml
oidc/userinfo/oidc-userinfo-stub.ts
oidc/userinfo/tests/oidc-userinfo-stub.test.ts

- Include userinfo stub to lint and test lambda workflow
- Update the code as per linting issues.
- Update the object type on the response object

OLH-922 : Add userinfo to lint and test lambda workflow

---

infrastructure/template.yaml

- Update the Stage as it is causing errors on deploy 
- https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/301577035144/projects/Deploy-account-mgmt-stubs-pipeline/build/Deploy-account-mgmt-stubs-pipeline%3Ace4de717-1854-4a4f-b536-2153706b8479/?region=eu-west-2

Update Stage for Api Mapping on Oidc stub

---

infrastructure/template.yaml

- Combing the 2 SSM parameter for userinfo and authorize endpoint of the OIDC stub into one OIDC endpoint SSM to be used by FE.

Update the SSM parameter to an OIDC endpoint

---

.github/workflows/sonarcloud-api.yaml
.github/workflows/sonarcloud-oidc-authorize.yaml
.github/workflows/sonarcloud-oidc-token.yaml
.github/workflows/sonarcloud-oidc-userinfo.yaml
account-management-api/sonar-project.properties
oidc/authorize/sonar-project.properties
oidc/token/sonar-project.properties
oidc/userinfo/sonar-project.properties

Update Sonar configurations.
Scope of work includes:
Create new Sonar projects within the [GOV.UK One Login](https://sonarcloud.io/organizations/govuk-one-login) organisation
- [account-management-stubs-oidc-userinfo](https://sonarcloud.io/project/overview?id=account-management-stubs-oidc-userinfo)
- [account-management-stubs-oidc-token](https://sonarcloud.io/project/overview?id=account-management-stubs-oidc-token)
- [account-management-stubs-oidc-authorize](https://sonarcloud.io/project/overview?id=account-management-stubs-oidc-authorize)
- [account-management-stubs-api](https://sonarcloud.io/project/overview?id=account-management-stubs-api)
Updated Sonar projects to point to the `main` branch instead of `master`
Create secrets for Sonar tokens
- SONAR_TOKEN_API 
- …

OLH-1236 Update Sonar organisation value to govuk-one-login

---

oidc/authorize/tests/oidc-authorize-stub.test.ts
oidc/token/tests/oidc-token-api-stub.test.ts
oidc/userinfo/oidc-userinfo-stub.ts

Make the stubs return the same user id (subject).  Make the email returned align with the onboarding manual.
Hardcode the user id.
Use same email address as the onboarding manual.
The user services table will no longer need to be changed each time someone logs into an envrionment.

OLH-1382 report suspicious activity

---

.github/CODEOWNERS
README.md
infrastructure/template.yaml

Add a Codeowners file and update the repo title and links after migration. I've already updated the trust policies for the actions.
We've moved this repository to the new Github organisation.

OLH-1129: Update links after migration

---

template.yaml

Correct typo.
Corrected name of handler for jwks function.
Fixes module not found error when attempting to run the lambda.

OLH-1691: fix typo.

---

.pre-commit-config.yaml
README.md

This will run prettier on all staged files before a new commit is created. If any files are modified, the hook will fail and we'll need to check and stage the changes.
To keep our formatting consistent and reduce the number of linting changes / commits we need to review.
See also:
https://github.com/govuk-one-login/di-account-management-frontend/pull/1271
https://github.com/govuk-one-login/di-account-management-backend/pull/220

BAU: Set up pre-commit to run prettier

---

template.yaml

Update method-management entrypoints so shared code can be found correctly
Previous merge broke our sam build
https://github.com/govuk-one-login/account-management-stubs/pull/58
Ran sam build and local start-api

OLH-1747 fix template entrypoints

---

src/method-management/method-management.ts
src/scenarios/scenarios.ts

Add the remaining scenarios for the stub API
So we can test the app in different states

OLH-1762 Create responses for the scenarios we want to test

---

src/tests/method-management/method-management.test.ts

Add a test to validate Auth app update request
The addition of a unit test specifically for auth app
To solidify the update flow stub changes.
NA
Tested auth app update in dev.
NA

OLH-1793-Verify-Stub-can-handle-Auth-App-updates

---

.github/workflows/publish-to-test.yaml

Added a GitHub workflow to publish to test account

Added a workflow to publish to test account

---

src/method-management/method-management.ts
src/scenarios/scenarios.ts
src/tests/method-management/method-management.test.ts

OLH-1798 Check the stub is validating the right things
Validate as per method management API requirement as described by auth team.
So that our stubs validation matches what will be done on actual method management api
https://govukverify.atlassian.net/browse/OLH-1798
See here Slack thread with Auth team: https://gds.slack.com/archives/C02KUCT0ZAS/p1717047721336049
Deploy to dev and test

OLH-1798 Check the stub is validating the right things

---

template.yaml

Adding "demo" URL in Mappings
[PSREDEV-1153]
Required for testing home stubs pipeline in test account
https://github.com/govuk-one-login/account-management-stubs/pull/165
[PSREDEV-1153]: https://govukverify.atlassian.net/browse/PSREDEV-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Psredev 1153 Adding "demo" URL in Mappings

---

src/oidc/authorize.ts

Adds a short explanation of what the scenario selector screen is about
People were getting confused when they saw i t

OLH-1886 Add a short explanation of the userScenarios buttons you see running our applications locally

---

.github/workflows/publish-to-demo.yaml
.github/workflows/publish-to-dev.yaml
.github/workflows/sam-app-post-merge-actions.yaml

Update the upload action to v3.9.1
This is required to use the new enriched build notifications feature.
See also https://github.com/govuk-one-login/di-account-management-backend/pull/275

BAU: Update the upload action to v3.9.1

---

.github/workflows/publish-to-demo.yaml
.github/workflows/publish-to-dev.yaml
.github/workflows/sam-app-post-merge-actions.yaml

Reverts govuk-one-login/account-management-stubs#186

Revert "BAU: Update the upload action to v3.9.1"

---

src/method-management/method-management.ts
src/tests/method-management/method-management.test.ts
template.yaml

Adds a new DELETE endpoint to the MFA method management stub API
To support us in developing and testing the delete MFA method workflow.
I deployed this to dev, and tested the lambda by testing at the API Gateway level through the console.

OLH-1967 Add delete endpoint to stub API

---

src/method-management/method-management.ts

This removes the check for email and otp when updating the field
Validation becomes quite complicated in the stub, as we don't always need the OTP or email (for example, if you are changing the default MFA method).
Rather than implementing complicated validation logic in this API, I have removed the validation in the first place.

OLH-1941 remove validation on update mfa method

---

src/account-management-api/all-routes.ts
src/scenarios/scenarios-utils.ts
src/scenarios/scenarios.interfaces.ts
src/scenarios/scenarios.ts
src/tests/account-management-api/all-routes.test.ts
template.yaml

- Add a new `otpNotification` scenario for testing
- Correctly set the error code when there is an error

OLH-2017 add scenario for already used mobile phone number

---

src/account-management-api/all-routes.ts
src/method-management/method-management.ts
src/method-management/models/schema.d.ts
src/oidc/token.ts
src/oidc/validate-token.ts
src/scenarios/scenarios-utils.ts
src/scenarios/scenarios.interfaces.ts
src/scenarios/scenarios.ts
src/tests/account-management-api/all-routes.test.ts
src/tests/method-management/method-management.test.ts
src/tests/oidc/token.test.ts
src/tests/oidc/validate-token.test.ts

[OLH-2053] Replaced mfamethod scheme to have SMS phone number instead of endpoint
1) mfa schema updated to differentiate between AUTH APP and SMS
2) replaced endpoint with phone number
In line with mfa api
Deployed updated stub and frontend to dev and changed phone number and added a new SMS mfa backup. 
[OLH-2053]: https://govukverify.atlassian.net/browse/OLH-2053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2053-endpoint-will-be-changed-to-phone-number-in-the-method-management-api

---

src/scenarios/scenarios-utils.ts
src/scenarios/scenarios.ts

[OLH-2214] Moved generate uuid outside of const
Moved generate uuid outside of const for performance test user
Not creating unique sessions
Deployed to dev

Olh 2114 activity history not being stored with OIDC 2

---

src/oidc/token.ts
template.yaml

Increase the memory on the lambda.
I did a bit of research and discovered that memory allocation impacts CPU size of lambda, by increasing the memory size of lambdas, it seems to have an impact on the dyanmodb lookup.

OLH-2252 Investigate Delay in logging in on dev

---

.env.test
.husky/_/husky.sh
package-lock.json
package.json
src/oidc/authorize.ts
src/oidc/configuration.ts
src/oidc/token.ts
src/scenarios/scenarios-utils.ts
src/tests/oidc/configuration.test.ts
src/tests/oidc/jkws.test.ts
src/tests/oidc/token.test.ts
src/tests/oidc/userinfo.test.ts
src/tests/oidc/validate-token.test.ts
template.yaml

Reverts govuk-one-login/account-management-stubs#379

Revert "Revert "OLH-2205-performance-testing-implementation-of-overload-protection-library-causing-http-503-errors-optimise-stub-memory" [skip]"

---

template.yaml

[OLH-2181] ApiGateway point to live versions 
Minor change to point API Gateway to the live lambda versions
[OLH-2181]: https://govukverify.atlassian.net/browse/OLH-2181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OLH-2181 ApiGateway point to live versions

---

.github/workflows/publish-to-demo.yaml
.github/workflows/publish-to-dev.yaml
.github/workflows/publish-to-test.yaml
.github/workflows/sam-app-post-merge-actions.yaml
template.yaml

BAU - Performance Optimisations
Previously provisioned concurrency was added to facilitate the NFR which had a high number of users per second. This NFR was set too high and did not take into account real world traffic. Whilst this NFR is being adjusted, we are reverting our configuration to save costs. 
Updated esbuild as the latest version has some performance optimisations.
Save costs ~$300 per month
Deployed to Dev and ran a performance test against it

Bau cost optimisations

---

src/method-management/models/schema.d.ts
src/scenarios/scenarios.interfaces.ts
src/scenarios/scenarios.ts
template.yaml

- Update endpoint for retrieve functionality to match new latest API changes for retrieveing MFA
- Update scenarios to match new MFA retrieve method and return valid data depending on input
To align the stubs to the new MFA API Schema

Add scenarios to match new mfa retrieve method.

---

src/method-management/models/schema.d.ts
src/scenarios/scenarios.interfaces.ts
src/scenarios/scenarios.ts
template.yaml

Reverts govuk-one-login/account-management-stubs#432

Revert "Add scenarios to match new mfa retrieve method."

---

src/method-management/method-management.ts

Fix don't expect mfaMethodType in update requests
This makes the change I intended to make in #460 but in the correct (update) lambda handler, instead of the create one.
#460

BAU: Fix don't expect mfaMethodType in update requests

---

.github/CODEOWNERS
CODEOWNERS

Moved CODEOWNERS file and corrected its contents
To ensure we are tagged as reviewers on PRs

Move and correct codeowners

---

src/oidc/authorize.ts
src/scenarios/scenarios-utils.ts

Reverts govuk-one-login/account-management-stubs#498

Revert "OLH-2808-update-stub-to-populate-data-using-default-user-id"

---

template.yaml

Added tags to stubs APIs so that they get associated with FMS WAFs
API tags
WAF work

OLH-3085: Added Regional Policy tags to stub APIs
